version: 2

updates:
- package-ecosystem: "pip"
  directory: "/backend/uclapi"
  schedule:
    interval: "weekly"
    day: "monday"
    time: "08:00"
    timezone: "Europe/London"
  open-pull-requests-limit: 25
  allow: 
    - dependency-type: "direct"
