version: "3.7"  # Requires Docker 18.06.0+

services:
  shibpostgres:
    image: localhost:5000/shibpostgres
    build:
      context: .
      dockerfile: shibpostgres.Dockerfile
    environment:
      POSTGRES_USER: ${SHIB_POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${SHIB_POSTGRES_PASSWORD}
      POSTGRES_DB: ${SHIB_POSTGRES_DATABASE}
    volumes:
      - shibpostgres_data:/var/lib/postgresql

  nginx-shib:
    image: localhost:5000/nginx-shib
    build:
      context: .
      dockerfile: nginx.Dockerfile
      args:
        POSTGRES_USERNAME: ${SHIB_POSTGRES_USERNAME}
        POSTGRES_PASSWORD: ${SHIB_POSTGRES_PASSWORD}
        POSTGRES_DATABASE: ${SHIB_POSTGRES_DATABASE}
        NGINX_BUILD: latest
        VERSION: ${UCLAPI_VERSION}
    depends_on:
      - shibpostgres
    volumes:
      - letsencrypt_config:/etc/letsencrypt/
    ports:
      - "80:80"
      - "443:443"

  uclapi:
    image: localhost:5000/uclapi
    build:
      context: ../../
      dockerfile: docker/deployment/uclapi.Dockerfile
    ports:
      - "9000:9000"

  # cron:
  #   image: localhost:5000/cron
  #   build:
  #     context: ../../
  #     dockerfile: docker/deployment/cron.Dockerfile

volumes:
  letsencrypt_config:
    driver: local
  shibpostgres_data:
    driver: local
