# Staging overlay Docker Compose
version: "3.7"

services:
  shibpostgres:
    image: 236848092535.dkr.ecr.eu-west-2.amazonaws.com/uclapi-staging-shibpostgres:latest
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
      restart_policy:
        condition: on-failure
      placement:
        # Constrain the Shibboleth Postgres instance to live on the non-public facing Manager
        constraints: [node.role == manager]

  traefik:
    image: traefik:v2.6
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
      restart_policy: on-failure
    command:
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --certificatesresolvers.leresolver.acme.httpchallenge=true
      - --certificatesresolvers.leresolver.acme.httpchallenge.entrypoint=web
      - --certificatesresolvers.leresolver.acme.email=isd-apiteam@ucl.ac.uk
      - --certificatesresolvers.leresolver.acme.storage=/acme.json
      - --entrypoints.web.http.redirections.entryPoint.to=websecure
      - --entrypoints.web.http.redirections.entryPoint.scheme=https
      - --entrypoints.web.http.redirections.entrypoint.permanent=true
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./storage/acme.json:/acme.json

  uclapi:
    image: 236848092535.dkr.ecr.eu-west-2.amazonaws.com/uclapi-staging-uclapi:latest
    build:
      args:
        ENVIRONMENT: staging
    labels:
      - traefik.enable=true
      - traefik.port=9000
      - traefik.http.routers.web.tls=true
      - traefik.http.routers.web.rule=Host(`staging.ninja`)
      - traefik.http.routers.web.entrypoints=websecure
      - traefik.http.routers.web.tls.certresolver=leresolver
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
      restart_policy:
        condition: on-failure

  cron:
    image: 236848092535.dkr.ecr.eu-west-2.amazonaws.com/uclapi-staging-cron:latest
    build:
      args:
        ENVIRONMENT: staging
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: ${CRON_CPU_COUNT}
          memory: ${CRON_MEMORY_KB}K
